name: "track"

on:
  schedule:
    - cron: '0 7 * * *'
  # Support manual trigger
  workflow_dispatch:

jobs:
  track:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./scripts/requirements.txt
      - name: Check Update
        id: check-update
        run: python ./scripts/check-update.py
      - name: Commit Changes
        # If `version` is not `none`
        if: steps.check-update.outputs.version != 'none'
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add versions.json
          git commit -m "Detected QQ update: ${{ steps.check-update.outputs.version }}"
          git push origin main
          echo "Successfully pushed changes (QQ updated to ${{ steps.check-update.outputs.version }})"
      - name: Download QQ
        # If `version` is not `none`
        if: steps.check-update.outputs.version != 'none'
        run: |
          mkdir -p downloads # Create directory `downloads` if not exists
          # Download QQ from URLs specified by `x64`, `x86` and `arm` under directory `downloads`, using default names specified by the URLs
          wget -P downloads ${{ steps.check-update.outputs.x64 }}
          wget -P downloads ${{ steps.check-update.outputs.x86 }}
          wget -P downloads ${{ steps.check-update.outputs.arm }}
      - name: Create Release
        # If `version` is not `none`
        if: steps.check-update.outputs.version != 'none'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.check-update.outputs.version }}
          files: |
            downloads/*
