name: "track"

on:
  schedule:
    - cron: '0 7 * * *'
  # Support manual trigger
  workflow_dispatch:

jobs:
  track:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./scripts/requirements.txt
      - name: Check Update
        id: check-update
        run: python check-update.py
      - name: Download QQ
        # If `version` is not `none`
        if: steps.check-update.outputs.version != 'none'
        run: |
          mkdir -p downloads # Create directory `downloads` if not exists
          # Download QQ from URLs specified by `x64`, `x86` and `arm` under directory `downloads`, using default names specified by the URLs
          wget -P downloads ${{ steps.check-update.outputs.x64 }}
          wget -P downloads ${{ steps.check-update.outputs.x86 }}
          wget -P downloads ${{ steps.check-update.outputs.arm }}
      - name: Create Release
        # If `version` is not `none`
        if: steps.check-update.outputs.version != 'none'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.check-update.outputs.version }}
          files: |
            downloads/*
